//! Phase 0 writer engine (Workstream B of `implementation-plan.md`).
//!
//! Day-major single chronological sweep over `bars_1m_raw/`, producing the
//! eight observation-pivot output tables (schemas in
//! `momentum_core::phase0_outputs`, RFC v7). Output mirrors the input
//! layout: `data/outputs/<table>/YYYY-MM-DD.parquet`, every file stamped
//! with the table's version constants via [`stamps`].
//!
//! ## Build state
//!
//! B0 (done): bulk day read (`MaterializedBarReader::day_sessions`),
//! session window slicing, SQLite resume cursor, metadata stamping.
//! B1 (in progress): chronological sweep with rolling per-security
//! trailing state ([`rolling`], fed by [`aggregates`]); the
//! `daily_observation` builder fills signal snapshots, EOD/premarket
//! aggregates, overnight context, and trailing windows. Files carry an
//! `engine_milestone` stamp; anything not stamped `complete` is partial
//! by construction and gets regenerated by a later milestone.

pub mod aggregates;
pub mod classification;
pub mod cursor;
pub mod daily_observation;
pub mod earnings;
pub mod market_context;
pub mod regimes;
pub mod rolling;
pub mod sector;
pub mod sic;
pub mod slices;
pub mod stamps;
